### ISSUE TITLE
Passphrase duplications - Yes/no?

### ISSUE THREAD

**Issue by sIurps** [worzel666/CM2301#1]
Check below within the while loop we've currently got it disallowing duplication, however we have designed it so multiple passphrases can be supported, so should we turn this off?

    def UserInput(): # Take user input
	    firstname = raw_input("Enter forename: ")
	    lastname = raw_input("Enter lastname: ")
	    passphrase = raw_input("Enter passphrase: ")
	    passphrase = passphrase.lower()

	    name = str(lastname)+"_"+str(firstname) # lastname_forename format for folder names

	
	   alphFolder()
	   while(True):
               with open("../passphrases.txt", "a+") as myfile:
	               if passphrase in myfile.read():
		               print "Already exists."
		               passphrase = raw_input("Enter passphrase: ") # If so, they must re-enter
		               passphrase = passphrase.lower()

		           else: 				
		               myfile.write(str(passphrase)+"\n")
		               CreateFolder(name, passphrase)
		               break

**Code snippet from:** Register.py

**Comment by worzel666** [comment]
What if 2 people have the same name and the same passphrase? I mean I think we should if we can but I am curious as to the security implications of this.

**Comment by sIurps** [comment]
That is a good point, maybe we should make it only disallow it if there's people with exactly the same name and passphrases?

**Comment by worzel666** [comment]
Yeah that sounds good I don't think there's any other way to uniquely identify someone who is entering.

**Comment by sIurps** [comment]
Fixed
